### ISSUE TITLE
EXOTica binary release checklist

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#421]
**Merge outstanding pull requests**

- [ ] Merge #394 
- [ ] Merge #401 
- [ ] Merge #417 
- [ ] Merge #420 

**Upstream local research changes**

- [ ] Visualization
- [ ] Exotica Core updates

**Rename packages, files, classes, methods, member variables, etc. according to style guide/convention**
Also check for correct header includes (not all of Exotica etc.), dead code, etc.

- [ ] ``exotica_examples``
- [ ] ``exotica_aico_solver``
- [ ] ``exotica_ik_solver``
- [ ] ``exotica_collision_scene_fcl``
- [ ] ``exotica_collision_scene_fcl_latest``
- [ ] ``exotica_core_taskmaps`` (<-- probably one of last to do, most outstanding research code changes)
- [ ] ``exotica_python``
- [ ] ``exotica``

**Release to ROS buildfarm**

- [ ] Add pr2 based unit test to complement/replace Valkyrie based on for release tests (only test Valkyrie on our own infrastructure)
- [ ] Bump versions to ``5.0`` and update all ``package.xml`` information
- [ ] Work around pybind11_catkin issue on melodic
- [ ] Release exotica core, solvers, task maps, examples, python to kinetic and melodic

**Update documentation**

- [ ] Update documentation for renaming and changes
- [ ] Push updated documentation online

**Comment by wxmerkt** [comment]
Release request made:

- Kinetic: https://github.com/ros/rosdistro/pull/19892
- Melodic: https://github.com/ros/rosdistro/pull/19894
